### ISSUE TITLE
how to collect the dataset

### ISSUE THREAD

**Issue by iiwindii** [CreativeInquiry/terrapattern#7]
Hi all, I have two queries: (1) How to label the downloaded image tiles in order to train CNN? As there are a large amount of image tiles, it is impossible to manually label them into different categories. (2) in the script  download_area.rb, the lngOffset should be changed according to the latitude. So why it is kept fixed in the script? Hope for your reply, thanks! @golanlevin @workergnome @irealva

**Comment by workergnome** [comment]
To answer (1), we used some of the other scripts in the latitude to identify categories of data using OSM.  

To answer (2), a small amount of overlap does not effect the quality of our results, and we felt it was easier to keep it static than to worry too much about perfection.  The features at a given lat/lng are there regardless if the image tile overlaps with another tile.  We do adjust this in the UI, but only per-city, not per-lat/lng.

**Comment by iiwindii** [comment]
@workergnome thanks for reply.  I want to collect a large dataset for my research paper using your scripts, but I'm a bit confused. I did not find the script to identify categories of data using OSM in the terrapattern repository. It is not included? Could you give some advice or some documents that I can refer to? Thanks!

**Comment by workergnome** [comment]
If you look at the Download Ways or Download Nodes folders in the repo, you'll find those scripts.  As far as identifying useful categories—we identified categories by hand.  There's not an automated way to decide which categories are most useful to your project, unfortunately.

**Comment by fengyunxiaozi** [comment]
@workergnome Thanks for your help! I know how to identify categories of data using OSM now. However, I met several problems when using the scripts in download_nodes folder:
(1) In the script download_nodes.rb, NUMBER_TO_DOWNLOAD=1000 is the nodes of each categories (if OSM has 1000 nodes) to download. However, when I run this script with features.csv file to download images from Google Map, I get fewer than 1000 images and the wrong information is as shown in the figure. I cannot figure out what's wrong with this, very strange.
(2) In features.csv file, even if the item "us_only" is set to true, the script still downloads some images that are not from US. Is this a bug?
(3) Each node defines  a location by lat/lng. However, if the categories I want are linear features such as river or road, the script download_nodes.rb may return you many images that are neither river nor road.  How to solve this problem?
Hope for your reply. Thanks!

**Comment by fengyunxiaozi** [comment]
@kylemcdonald @irealva @aman-tiwari anyone could help with these peoblems? Thanks!
